package com.codeheadsystems.hofmann.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Client's OPRF request: { ecPoint, requestId }.
 *
 * @param hexCodedEcPoint A hex-encoded elliptic curve point generated by the client after blinding the hashed data.
 * @param requestId       A unique identifier for this request, which can be used for tracking and correlation with the server's response.
 */
public record OprfRequest(@JsonProperty("ecPoint") String hexCodedEcPoint,
                          @JsonProperty("requestId") String requestId) {
}
