package com.codeheadsystems.rfc.oprf.model;

/**
 * The request sent to the server for elimination.
 *
 * @param blindedPoint The hex-encoded elliptic curve point generated by the client after blinding the hashed data.
 * @param requestId    A unique identifier for this request, which can be used for tracking and correlation with the server's response.
 */
public record BlindedRequest(String blindedPoint, String requestId) {
}
