package com.codeheadsystems.hofman;

/**
 * The request sent to the server for elimination.
 *
 * @param clientKeyIdentifier Client registered key used during the binding process.
 * @param hexCodedEcPoint The hex-encoded elliptic curve point generated by the client after blinding the hashed data.
 * @param requestId A unique identifier for this request, which can be used for tracking and correlation with the server's response.
 */
public record EliminationRequest(String clientKeyIdentifier, String hexCodedEcPoint, String requestId) {
}
