package com.codeheadsystems.hofmann.model.oprf;

import com.codeheadsystems.rfc.oprf.model.BlindedRequest;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Client's OPRF request: { ecPoint, requestId }.
 *
 * @param ecPoint   A hex-encoded elliptic curve point generated by the client after blinding the hashed data.
 * @param requestId A unique identifier for this request, which can be used for tracking and correlation with the server's response.
 */
public record OprfRequest(@JsonProperty("ecPoint") String ecPoint,
                          @JsonProperty("requestId") String requestId) {

  /**
   * Instantiates a new Oprf request.
   *
   * @param blindedRequest the blinded request
   */
  public OprfRequest(BlindedRequest blindedRequest) {
    this(blindedRequest.blindedPoint(), blindedRequest.requestId());
  }

  /**
   * Blinded request blinded request.
   *
   * @return the blinded request
   */
  public BlindedRequest blindedRequest() {
    return new BlindedRequest(ecPoint(), requestId());
  }

}
