/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    idea

    // Minimum versions for transitive dependencies with published advisories. Applied here so
    // every module gets them, since the vulnerable artifacts arrive through the frameworks
    // rather than being declared anywhere.
    id("buildlogic.security-floor-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()  // was jcenter() which is dying
    google()

    maven("https://oss.sonatype.org/content/repositories/snapshots/")
    maven("https://oss.sonatype.org/content/repositories/releases/")
    maven("https://s3-us-west-2.amazonaws.com/dynamodb-local/release/")
}

dependencies {

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withJavadocJar()
    withSourcesJar()
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

// Ensure we have lint warnings displayed so we can fix or  @SuppressWarnings("unchecked")
tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-Xlint:unchecked")
}

tasks.javadoc {
    if (JavaVersion.current().isJava9Compatible) {
        (options as StandardJavadocDocletOptions).addBooleanOption("html5", true)
    }
    // Javadoc warnings fail the build. This is a published library, so a missing @param or a
    // stale @link is a defect in the artifact consumers actually read, not a lint nit — and
    // warnings that do not fail accumulate until nobody reads them. The backlog was driven to
    // zero before this was switched on.
    (options as StandardJavadocDocletOptions).addBooleanOption("Werror", true)
}
