package com.codeheadsystems.rfc.opaque;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.codeheadsystems.rfc.common.ByteUtils;
import com.codeheadsystems.rfc.opaque.config.OpaqueCipherSuite;
import com.codeheadsystems.rfc.opaque.config.OpaqueConfig;
import com.codeheadsystems.rfc.opaque.model.AuthResult;
import com.codeheadsystems.rfc.opaque.model.ClientAuthState;
import com.codeheadsystems.rfc.opaque.model.ClientRegistrationState;
import com.codeheadsystems.rfc.opaque.model.KE2;
import com.codeheadsystems.rfc.opaque.model.RegistrationRequest;
import com.codeheadsystems.rfc.opaque.model.Envelope;
import com.codeheadsystems.rfc.opaque.model.RegistrationRecord;
import com.codeheadsystems.rfc.opaque.model.RegistrationResponse;
import com.codeheadsystems.rfc.opaque.model.ServerAuthState;
import com.codeheadsystems.rfc.opaque.model.ServerKE2Result;
import java.math.BigInteger;
import org.bouncycastle.util.encoders.Hex;
import org.junit.jupiter.api.Test;

/**
 * Cross-implementation OPAQUE conformance vectors for P384-SHA384, P521-SHA512 and
 * Ristretto255-SHA512.
 * <p>
 * Unlike {@link OpaqueVectorsTest} (P256-SHA256), the CFRG/RFC 9807 specification publishes
 * <em>no</em> official OPAQUE known-answer vectors for these three suites. To guard against
 * suite-specific encoding/KDF divergence that a self-consistent round-trip cannot catch, the
 * expected bytes below were generated by the <em>independent</em> Rust implementation
 * (hofmann-rust, tests/cross_impl_gen.rs) running the identical deterministic flow with the
 * identical fixed inputs. Two independent implementations agreeing byte-for-byte on the full
 * registration + AKE wire format is real conformance evidence and pins cross-language interop.
 * <p>
 * To regenerate after an intentional wire-format change, run in hofmann-rust:
 * {@code cargo test --test cross_impl_gen -- --nocapture} and update both sides together.
 */
class OpaqueCrossImplVectorsTest {

  private static byte[] hex(String s) {
    return Hex.decode(s);
  }

  private static byte[] reverse(byte[] bytes) {
    byte[] out = new byte[bytes.length];
    for (int i = 0; i < bytes.length; i++) {
      out[i] = bytes[bytes.length - 1 - i];
    }
    return out;
  }

  /** Decodes a blind scalar from hex, honouring ristretto255's little-endian scalar encoding. */
  private static BigInteger scalar(Vector v, String hexBytes) {
    byte[] bytes = hex(hexBytes);
    if (v.suite() == OpaqueCipherSuite.RISTRETTO255_SHA512) {
      // Interpret the little-endian scalar bytes as a big-endian BigInteger.
      bytes = reverse(bytes);
    }
    return new BigInteger(1, bytes);
  }

  /**
   * The server's static private key, fed to Java exactly as the Rust generator emitted it.
   *
   * <p>This used to reverse the ristretto255 bytes, because Java's {@code Server} constructor read
   * every suite's scalar big-endian while the Rust generator emits ristretto255 little-endian per
   * RFC 9496. That reversal was the divergence, not a detail of the harness: it meant these
   * vectors passed while the two implementations disagreed about what a given 32-byte ristretto255
   * private key denotes, so the one test positioned to catch it was compensating for it instead.
   *
   * <p>{@code Server} now decodes through {@code GroupSpec.deserializeScalar}, which is
   * per-suite canonical, so the bytes cross unmodified and this is a real cross-implementation
   * check on all four suites. Removing the reversal is what makes the check meaningful; if this
   * ever needs to come back, the encodings have diverged again.
   */
  private static byte[] serverPrivateKey(Vector v) {
    return hex(v.serverPrivateKey());
  }

  // Shared fixed inputs (identical across suites where width-independent).
  private static final byte[] PASSWORD = hex("436f7272656374486f72736542617474657279537461706c65");
  private static final byte[] CREDENTIAL_IDENTIFIER = hex("31323334");
  private static final byte[] ENVELOPE_NONCE = hex("a1a0a3a2a5a4a7a6a9a8abaaadacafaeb1b0b3b2b5b4b7b6b9b8bbbabdbcbfbe");
  private static final byte[] CLIENT_NONCE = hex("b2b3b0b1b6b7b4b5babbb8b9bebfbcbda2a3a0a1a6a7a4a5aaaba8a9aeafacad");
  private static final byte[] CLIENT_KEYSHARE_SEED = hex("c3c2c1c0c7c6c5c4cbcac9c8cfcecdccd3d2d1d0d7d6d5d4dbdad9d8dfdedddc");
  private static final byte[] MASKING_NONCE = hex("d4d5d6d7d0d1d2d3dcdddedfd8d9dadbc4c5c6c7c0c1c2c3cccdcecfc8c9cacb");
  private static final byte[] SERVER_NONCE = hex("e5e4e7e6e1e0e3e2edecefeee9e8ebeaf5f4f7f6f1f0f3f2fdfcfffef9f8fbfa");
  private static final byte[] SERVER_KEYSHARE_SEED = hex("f6f7f4f5f2f3f0f1fefffcfdfafbf8f9e6e7e4e5e2e3e0e1eeefecedeaebe8e9");

  /** Per-suite inputs and expected (Rust-generated) wire outputs. */
  private record Vector(
      OpaqueCipherSuite suite,
      String serverPrivateKey,
      String serverPublicKey,
      String oprfSeed,
      String blindRegistration,
      String blindLogin,
      String registrationRequest,
      String registrationResponse,
      String registrationUpload,
      String ke1,
      String ke2,
      String ke3,
      String sessionKey,
      String exportKey) {
  }

  private static final Vector P384 = new Vector(
      OpaqueCipherSuite.P384_SHA384,
      "24d6f6400de5fd8afdf09c2be8be9ae29f06d518b685cb7f3194f7453680a8e614e5067d881d805e5ef5e01969e60f9d",
      "023982e1ab05a7dfc88cee02799a0a113ac66b20f4a4ab34d47c418f34ce17e967113d60625639f1c7829f4f4fc3c7d230",
      "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f000102030405060708090a0b0c0d0e0f",
      "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042",
      "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000037",
      "0322caa3299f5c998833ca8d96a3675988f893deb7c976e6a52024849c4918ad2563ef1949df82738d709ff1e4eb603d7a",
      "02904e43e430bc6fcd11444b1abdd105f4a6e648e71e8aa4b81b6ae94f2cd6491947f77777c3dd2cb7cbb06c139c26d930023982e1ab05a7dfc88cee02799a0a113ac66b20f4a4ab34d47c418f34ce17e967113d60625639f1c7829f4f4fc3c7d230",
      "034b6c5d5ddda28c9c46b0054ba462ea00da8833794578abaae86f56561e2ccf206d36608998acd2c531bdd5de5cb27f89ee4d224678ca31eab16745428027fc414493ce2603bca9325fed59bf952264273798c2f8537db03b7181ce667ba12046a1a0a3a2a5a4a7a6a9a8abaaadacafaeb1b0b3b2b5b4b7b6b9b8bbbabdbcbfbe802815269bb6dcf802265747d2650637f0ae1202a218106d1c6c3eee4aa383dce885c9ec273129fe301dbae99f35b55e",
      "03f8a0170232ff7c069e14b1c564c7704ac08d67f02d88f645f4fe5a774a8005d18aacb055ffce2b516d05f16bdd0d577bb2b3b0b1b6b7b4b5babbb8b9bebfbcbda2a3a0a1a6a7a4a5aaaba8a9aeafacad033d8df0d355dbb8f00e11ecb75ca4321c5e35ee65b642f0be47ccdaa6596ee70ee488855574b80e95cecc18652bc7d7f9",
      "0381c50e5f61305d4fc68ea45306e111bd20410452f3e5315afb9f251be3b10bd62d55f980e1fdffe5b2a910391a2aa77fd4d5d6d7d0d1d2d3dcdddedfd8d9dadbc4c5c6c7c0c1c2c3cccdcecfc8c9cacba77661d26842b92b19b6a9d13efaa5566659e05cf3cc85ce730b8f4c2337ff37f007192e3e07adf7425e0b21faaeb398bdcc3306af46ca32ba3bcd6c0927fa08a0f7be69b4e168e2d0ce866a49fd9b33d843232ad2f2b6745ba2411fde50f328ed3b8d0451bb509e474994a74f994cb22118ded48f55bdd1da35e66717ecfd94fae5e4e7e6e1e0e3e2edecefeee9e8ebeaf5f4f7f6f1f0f3f2fdfcfffef9f8fbfa0365504fbdf91a4c07024fcb60f45df5439d3ac9b8c982a5d3ed4dc21577a0e586b04bd5bd2c4c1ce9a30ced977b32e57f9f9dff78dd97a49a10763a3150d967585db837e6318dcb49dc8a17655a11bb95ba058c1457a9bda68629e2b6b33dd3f4",
      "a144344125dd67081f52f4a5ad4267610032bffe4cebd35b509427048c7f09a887f986feea0dafcfdd413782543d5054",
      "77bf1c3314db54234ada1a73dd1326988149343b82a99d032edff86c2941c492e49fc4d3a8315fcbb28ea6becebda13d",
      "02459b8eb37bc148f63fc48b7ac72f71b916dadd0a65c21282ff6dc2aec50a03204c2794640617f1ea7281767d5622a9");

  private static final Vector P521 = new Vector(
      OpaqueCipherSuite.P521_SHA512,
      "01561604d1ee1effbb196d4a2149a9b04619afda33a1a5b1ae1c7ae843a261187b4657ebafc76720ca62eddce151bd42b1ed3a657b22d439f1d99068388efed6bbe5",
      "0201adfd9c448a3c1712e2421abb34f07432715ae1c993cff5f5c7732f632bd1639fc9cec71ce0578e930135c58aa1261431b30888bc47be60e64b773ff99851173a2e",
      "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
      "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042",
      "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000037",
      "0201211122a5c04001bfecd3902422bdfd849ccb478e7bdf1f2fd4b5780fd2ca15a833615d20c5fea13ec58f805b75af733dc742ca4265aa9d9a06356745f8244e8cc4",
      "0300e61acb078b162ea94796abc8bcccf52d75bad54a6c6af51a1162c73e7ebe458bcaac65703e6d3c78a9e601ea3742e4b1804dbd61686245b842179bb2b2701fdc5f0201adfd9c448a3c1712e2421abb34f07432715ae1c993cff5f5c7732f632bd1639fc9cec71ce0578e930135c58aa1261431b30888bc47be60e64b773ff99851173a2e",
      "03005bc61744cb59415008ab399129fe01344a3bb43373cca66dc8d24c31acfb524115bdaa26ee3362bb1c721f94f1430d535426df5b498d65340878671244fe522e954ba5927c55565cc70be74467f4d7d56111cc42d8ad71762007e3e78e903627b75b776b18b39ffcd02201d45365846be38fe2d4454ebe8df10927d67c8b236ddca1a0a3a2a5a4a7a6a9a8abaaadacafaeb1b0b3b2b5b4b7b6b9b8bbbabdbcbfbeaff7e5423ddeea8d5f1e820c5103fd9d409e793b70285f8920a525fd1da692abefb8cd9d6ddaaed8c9e89dd85e1f0f4f6c098870a4fb543a215bdae42c599fdd",
      "03006b0400183c327d12d26be41c0cfd6da6fff4b23f36f44714a3d05a17ba53ed0dd2f503afcb8df2cdfd3878422f56c95ab50244df704ff452c5c3a7284a63f42091b2b3b0b1b6b7b4b5babbb8b9bebfbcbda2a3a0a1a6a7a4a5aaaba8a9aeafacad0301daf21c26f55165bda37cb78dc7163058d29a66aa341587b259766b520cd0a274300b24230173e281e6e06c37c251673dc80544f10049334bb5b06fb628cd2663d1",
      "020014906e708ea392aea2f56de7a3f9b0a5b89ccf23696a4c1474a7aa5c0f79a45fee48c71b4cba500eed6632470ffae412e5e3d30c4deed23ac492c0d4fada000319d4d5d6d7d0d1d2d3dcdddedfd8d9dadbc4c5c6c7c0c1c2c3cccdcecfc8c9cacb60514c08b833104b620bcc27f79718fe7fffdc32ae4c7e36d614ac9e250a8c275f41590a8135b256d6afe4a0096e15f9dd892b33d628fbb3f1d202217e1e0f64394275edfd636dc26547cd23d95514503ee9ebd9e90141ecc1a347ce41559e557d9dc13b881710331e6bbaa57ca2b3f76a194e7b66ba5151afc91fdf7398e32aaa5d75d319b8aa717a619218a0f66e40d688ecc22c4b094c1edffc502af20b9e040c95e5e4e7e6e1e0e3e2edecefeee9e8ebeaf5f4f7f6f1f0f3f2fdfcfffef9f8fbfa03010815c4ac85f5089c213e60ed2044ffa05f01b12e8a02ae58c44d95bbb73a7d8ef16cbca18d1f301c5ea2cf45b1f9ecd98361541ce56049bbc62210002f4181cacee84a7a26eb3352f2e10065efc7869a76ab8ad8333ae1bb0aee80fa0e33cb3f6888d6e5b1fa1c323a698664082fd716ab34bf7d5d4924c2e462aa2003e6b4d9e3",
      "b9c55c58d2e376f52405d6aee8cac94c586b0c238370aa0ba9308903b3d2afb05b146fe6cf8f4b65294d367a74404331cd8fdc5c3a2eb6aa99bd6a1619a3fd7c",
      "0cb35dd9e0b6593197f411986678b8ce2e3c7cdbf47aef256f684fae58083df97fd6c9f7e2a817c830396ec8d48164b7acd99b2fe75886ed4db650c2568d5c12",
      "23c391f0011200c26526806d818ffc135cf676244b8b0ceedec9abaddfa36489ab500f4ecf925a1fbf3a2299a6c4b5d931c3584e829e95587913f9567cae84fc");

  private static final Vector RISTRETTO255 = new Vector(
      OpaqueCipherSuite.RISTRETTO255_SHA512,
      "38a807fb081974a83fdfd09d144f2fd315ffa6cb7f3b617d2367cc3347629b03",
      "84c71b9b466eb89fe088b873b0044ca219ddd69db4841f18aa3cf37a24da6f57",
      "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
      "0000000000000000000000000000000000000000000000000000000000000042",
      "0000000000000000000000000000000000000000000000000000000000000037",
      "36562023f643d016f928a21befe21938d61c0e37d2606114b59bce285abf2f51",
      "949ece8d516d52ea21ac8008f01e4d36d0fc67337c56aadedd868445d7afae1f84c71b9b466eb89fe088b873b0044ca219ddd69db4841f18aa3cf37a24da6f57",
      "e67e7160c06cfba2adaca8c269e8a7383663684b287fe77dbdabdead579f1e3db505c655b2df656393c8e5742cf743492c3ca7e8b81875e1b85d032ae9733a184e7da0af3e17e5afba2cb82c320451f42010092d33fc0438f39fde918e621acaa1a0a3a2a5a4a7a6a9a8abaaadacafaeb1b0b3b2b5b4b7b6b9b8bbbabdbcbfbefcf66396739ae3bfdd36ca41143eccf7383a2e5ea71479585c8d466f0c33b6585a8490309b3199f55cae965bda5a01d9dcdde92bf9c6aebba98f79befb39fb0b",
      "60fc339f1b423ad7f11b16cf29f4c4ebfac25597b9fd77d51029f850fd941d43b2b3b0b1b6b7b4b5babbb8b9bebfbcbda2a3a0a1a6a7a4a5aaaba8a9aeafacad04e51098d75eedc7090db9558a3008ad551cff2bd2a1cafb795ca9e72990e834",
      "841bb5de342cfeec1055b84306037100bfe8fb306a6dbe98c242eaaf6598f32dd4d5d6d7d0d1d2d3dcdddedfd8d9dadbc4c5c6c7c0c1c2c3cccdcecfc8c9cacb539034c6121c8a25fa1ed3d484c87d0f94d4992e05df86b00e8981009c4c249257f1c3ad8370b9c48e61d08b54a7bbfd517b58df47607baebab14ee50db6790acae531691a943b419395344a57330532d78b2fd22b8245337e0d1821c33900acdae39025c3b45af57d7ba6e3d0062bee1d288842d5b6f3ca20fb0e71c9ef8444e5e4e7e6e1e0e3e2edecefeee9e8ebeaf5f4f7f6f1f0f3f2fdfcfffef9f8fbfac00a21c998c063849fd8e30c5980d9c9b7e041e82a035b85876931d2fa6b294ce417a4db9cf5393e6a56497fe09249da8bb57e5524d7994c58cbcc53a3d8f4da8a4e1f58c4668b018d14a816425c567f89243c6dacc2cf90caa875b8b49155c3",
      "1f3d39f56cc23fb22aec0ba144eeec1b18d8b6f0c0724bd0fa9345c48465a6a9dad3d10f4713a84ecc086d6180fdca3bee41a0b3cc848c31ed652f6b12229add",
      "4c5ad0071bc714b628665ac252954499d3684cf61950c6d6fd3abda9aaea5f2ca1fdc823cc47de94808b9d1e39a5cf5e34e18259a99b0f55a91a43818c1e3035",
      "8f93940b18835ce4a87bc6ceb7caea656912127a790f1129c2cf6f3144152c005cc54d40246755886a9863df5e722cf30062d79c123cc2e700b0a89062243ba9");

  @Test
  void p384_matchesRustImplementation() {
    assertSuite(P384);
  }

  @Test
  void p521_matchesRustImplementation() {
    assertSuite(P521);
  }

  @Test
  void ristretto255_matchesRustImplementation() {
    assertSuite(RISTRETTO255);
  }

  private void assertSuite(Vector v) {
    OpaqueConfig config = OpaqueConfig.forTesting(v.suite());
    Client client = new Client(config);
    Server server = new Server(serverPrivateKey(v), hex(v.serverPublicKey()), hex(v.oprfSeed()), config);

    // The Rust generator feeds the blind as raw scalar bytes in each suite's canonical encoding;
    // ristretto255 scalars are little-endian (RFC 9496/9497) while the NIST suites are big-endian.
    // The Java deterministic API takes the blind as a BigInteger, so decode the same bytes with the
    // matching endianness to drive both implementations with the identical scalar value.
    BigInteger blindRegistration = scalar(v, v.blindRegistration());
    BigInteger blindLogin = scalar(v, v.blindLogin());

    // Registration.
    ClientRegistrationState regState = client.createRegistrationRequestDeterministic(PASSWORD, blindRegistration);
    assertThat(regState.request().blindedElement()).isEqualTo(hex(v.registrationRequest()));

    RegistrationResponse response = server.createRegistrationResponse(regState.request(), CREDENTIAL_IDENTIFIER);
    assertThat(ByteUtils.concat(response.evaluatedElement(), response.serverPublicKey()))
        .isEqualTo(hex(v.registrationResponse()));

    RegistrationRecord record = client.finalizeRegistrationDeterministic(
        regState, response, null, null, ENVELOPE_NONCE);
    assertThat(ByteUtils.concat(record.clientPublicKey(), record.maskingKey(), record.envelope().serialize()))
        .isEqualTo(hex(v.registrationUpload()));

    // Authentication.
    ClientAuthState authState = client.generateKE1Deterministic(
        PASSWORD, blindLogin, CLIENT_NONCE, CLIENT_KEYSHARE_SEED);
    assertThat(authState.ke1().serialize()).isEqualTo(hex(v.ke1()));

    ServerKE2Result ke2Result = server.generateKE2Deterministic(
        null, record, CREDENTIAL_IDENTIFIER, authState.ke1(),
        null, MASKING_NONCE, SERVER_KEYSHARE_SEED, SERVER_NONCE);
    KE2 ke2 = ke2Result.ke2();
    byte[] ke2Bytes = ByteUtils.concat(
        ke2.serializeCredentialResponse(), ke2.serverNonce(), ke2.serverAkePublicKey(), ke2.serverMac());
    assertThat(ke2Bytes).isEqualTo(hex(v.ke2()));

    AuthResult authResult = client.generateKE3(authState, null, null, ke2);
    assertThat(authResult.ke3().clientMac()).isEqualTo(hex(v.ke3()));
    assertThat(authResult.sessionKey()).isEqualTo(hex(v.sessionKey()));
    assertThat(authResult.exportKey()).isEqualTo(hex(v.exportKey()));

    // Server confirms the client MAC and derives the same session key.
    ServerAuthState serverAuthState = ke2Result.serverAuthState();
    byte[] serverSessionKey = server.serverFinish(serverAuthState, authResult.ke3());
    assertThat(serverSessionKey).isEqualTo(hex(v.sessionKey()));
  }

  // ─── error paths, per curve ────────────────────────────────────────────────
  //
  // The vectors above are happy-path by construction: the Rust generator emits what a correct
  // exchange produces, so every assertion here says "Java agrees with Rust when both behave".
  // That leaves the more interesting half untested — whether the two implementations agree on
  // what to *reject*. A divergence there is exactly the kind that ships: Java accepts something
  // Rust refuses, both pass their own suites, and the disagreement only surfaces when a real
  // client meets a real server.
  //
  // These take each suite's own vector and corrupt it in the specific ways the RFCs require to be
  // refused, asserting rejection at the same entry points the happy path uses. They live beside
  // the positive vectors deliberately: if a suite regresses, the failure lands next to the
  // evidence of what it used to do.

  @Test
  void p384_rejectsCorruptedVectors() {
    assertRejections(P384);
  }

  @Test
  void p521_rejectsCorruptedVectors() {
    assertRejections(P521);
  }

  @Test
  void ristretto255_rejectsCorruptedVectors() {
    assertRejections(RISTRETTO255);
  }

  private void assertRejections(Vector v) {
    OpaqueConfig config = OpaqueConfig.forTesting(v.suite());
    Server server = new Server(serverPrivateKey(v), hex(v.serverPublicKey()), hex(v.oprfSeed()),
        config);
    Client client = new Client(config);

    // The identity element as a blinded element. blindInv * O = O, so accepting it collapses the
    // OPRF output to a function of the input alone — independent of the blind and the server key.
    byte[] identity = identityEncoding(v.suite());
    assertThatThrownBy(() -> server.createRegistrationResponse(
        new RegistrationRequest(identity), CREDENTIAL_IDENTIFIER))
        .as("%s must refuse the identity as a blinded element", v.suite())
        .isInstanceOfAny(SecurityException.class, IllegalArgumentException.class);

    // A truncated blinded element: shorter than the suite's element size.
    byte[] full = hex(v.registrationRequest());
    byte[] truncated = java.util.Arrays.copyOf(full, full.length - 1);
    assertThatThrownBy(() -> server.createRegistrationResponse(
        new RegistrationRequest(truncated), CREDENTIAL_IDENTIFIER))
        .as("%s must refuse a truncated blinded element", v.suite())
        .isInstanceOfAny(SecurityException.class, IllegalArgumentException.class);

    // A blinded element that is the right length but out of range: every coordinate byte set.
    // Deterministic rather than a bit-flip — flipping bits in x lands back on the curve about half
    // the time, since y^2 = f(x) is a quadratic residue for roughly half of all x, so a corruption
    // test built that way passes or fails depending on the vector. All-ones exceeds the field
    // prime on every NIST curve here and fails ristretto255's s < p canonicity check, so it is
    // refused on all four for a reason each suite states.
    byte[] outOfRange = new byte[full.length];
    java.util.Arrays.fill(outOfRange, (byte) 0xff);
    if (v.suite() != OpaqueCipherSuite.RISTRETTO255_SHA512) {
      outOfRange[0] = 0x02;                    // valid SEC1 prefix, impossible coordinate
    }
    assertThatThrownBy(() -> server.createRegistrationResponse(
        new RegistrationRequest(outOfRange), CREDENTIAL_IDENTIFIER))
        .as("%s must refuse an out-of-range blinded element", v.suite())
        .isInstanceOfAny(SecurityException.class, IllegalArgumentException.class);

    // Non-canonical encoding: right length, wrong SEC1 type byte. RFC 9497 section 2.1 requires
    // DeserializeElement to be the inverse of SerializeElement, which only ever emits compressed.
    if (v.suite() != OpaqueCipherSuite.RISTRETTO255_SHA512) {
      byte[] wrongPrefix = full.clone();
      wrongPrefix[0] = 0x04;
      assertThatThrownBy(() -> server.createRegistrationResponse(
          new RegistrationRequest(wrongPrefix), CREDENTIAL_IDENTIFIER))
          .as("%s must refuse a non-compressed encoding", v.suite())
          .isInstanceOfAny(SecurityException.class, IllegalArgumentException.class);
    }

    // A registration record whose fields are the right shape but whose client public key is the
    // identity. This is the record-validation path every write endpoint runs.
    byte[] upload = hex(v.registrationUpload());
    int npk = config.Npk();
    byte[] badRecord = upload.clone();
    java.util.Arrays.fill(badRecord, 0, npk, (byte) 0x00);
    RegistrationRecord withIdentityKey = new RegistrationRecord(
        java.util.Arrays.copyOfRange(badRecord, 0, npk),
        java.util.Arrays.copyOfRange(badRecord, npk, npk + config.Nh()),
        record(upload, config).envelope());
    assertThatThrownBy(() -> server.validateRegistrationRecord(withIdentityKey))
        .as("%s must refuse a record whose client public key is the identity", v.suite())
        .isInstanceOfAny(SecurityException.class, IllegalArgumentException.class);

    // A KE2 with a corrupted server MAC must fail client-side authentication rather than being
    // accepted — the check that stops a server impersonating the one the client registered with.
    ClientAuthState authState = client.generateKE1Deterministic(
        PASSWORD, scalar(v, v.blindLogin()), CLIENT_NONCE, CLIENT_KEYSHARE_SEED);
    byte[] ke2Bytes = hex(v.ke2()).clone();
    ke2Bytes[ke2Bytes.length - 1] ^= (byte) 0xff;
    KE2 tamperedKe2 = KE2.deserialize(config, ke2Bytes);
    assertThatThrownBy(() -> client.generateKE3(authState, null, null, tamperedKe2))
        .as("%s must refuse a KE2 whose server MAC does not verify", v.suite())
        .isInstanceOfAny(SecurityException.class, IllegalArgumentException.class);
  }

  /** Each suite's canonical identity encoding; they differ, which is why this is not shared. */
  private static byte[] identityEncoding(OpaqueCipherSuite suite) {
    return suite == OpaqueCipherSuite.RISTRETTO255_SHA512 ? new byte[32] : new byte[]{0x00};
  }

  /** Splits a serialized registration upload back into a record. */
  private static RegistrationRecord record(byte[] upload, OpaqueConfig config) {
    int npk = config.Npk();
    int nh = config.Nh();
    return new RegistrationRecord(
        java.util.Arrays.copyOfRange(upload, 0, npk),
        java.util.Arrays.copyOfRange(upload, npk, npk + nh),
        Envelope.deserialize(upload, npk + nh, OpaqueConfig.Nn, config.Nm()));
  }
}
